### PR TITLE
Dev mobile work about section

### PR DESCRIPTION
**Pull request by uisendy**
My Port Folio: Mobile Version- Work and about section

### CODE REVIEW

**Review by cynthiainga — CHANGES_REQUESTED** [review]
Hi @uisendy , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- [ ] All linters are passing :heavy_check_mark: 
- [ ] Good implementation if the UI :heavy_check_mark: 
- [ ] Pull Request have a descriptive title :heavy_check_mark: 

## Required Changes ♻️

- [ ] Please make sure your README.md file is present in the `Files changed` :upside_down_face: :upside_down_face: then we can make sure that your README file is descriptive and if not we can help you to improve it. Just make some modifications to it and then commit it. Use [this template](https://github.com/microverseinc/readme-template/blob/master/README.md).
- [ ] Your Pull Request should have a short summary describing introduced changes in more detail :grin: :grin:. Please make sure to update it.
- [ ] Your commit messages should be meaningful, your git commit message does not follow the standard of using an infinitive verb to start the comment like `Add`, `Update` `Refactor`.
For example instead of `Updated README file` :point_right:  `Update README file`,  `Added background image` :point_right: `Add background image". So please make sure follow this rule in your next commit message.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by uisendy** [comment]
Thanks [cynthiainga](https://github.com/cynthiainga) for the honest review. Highly appreciated.

**Review by KayLemba — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hello  @uisendy        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by uisendy** [comment]
Thanks [KayLemba](https://github.com/KayLemba) for the optional review.

**Pull request merged**
